version: "3.8"
services:
  private:
    restart: unless-stopped
    image: $IMAGE_TAG
    container_name: private
    healthcheck:
      start_period: 20s
      test: ["CMD", "pgrep", "node"]
      interval: 15s
      timeout: 10s
      retries: 5
    environment:
      - IS_LOGGER
      - PORT
      - PG_HOST
      - PG_PORT
      - PG_USER
      - PG_PASSWORD
      - PG_DATABASE
      - RMQ_URL
      - RMQ_USER
      - RMQ_PASSWORD
      - RMQ_QUEUE_AGGREGATOR
      - RMQ_QUEUE_PRIVATE
    ports:
      - '3002:3002'
    networks:
      - default
